CREATE TABLE `t_node` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `eng_name` varchar(50) DEFAULT NULL COMMENT '栏目英文标识',
  `title` varchar(50) DEFAULT NULL COMMENT '栏目标题',
  `channel_id` int(11) DEFAULT NULL COMMENT '频道ID',
  `root_id` int(11) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL COMMENT '父节点ID，若为根节点值为0',
  `left_val` int(11) DEFAULT NULL COMMENT '预排序遍历树左值',
  `right_val` int(11) DEFAULT NULL COMMENT '预排序遍历树右值',
  `level` int(11) DEFAULT '0' COMMENT '节点层数，Root节点为层数0',
  `order` int(11) DEFAULT '0' COMMENT '节点同级顺序，从0开始',
  `type` int(11) DEFAULT '1' COMMENT '节点类型。1为容器栏目，3为单页节点，4为外部链接',
  `item_model_type` int(11) DEFAULT NULL COMMENT '结点内容模型类型，1为文章类型，2为图片新闻类型，3为视频类型，4为附件下载类型',
  `parent_path` varchar(255) DEFAULT NULL,
  `seo_keywords` varchar(255) DEFAULT NULL,
  `seo_description` varchar(255) DEFAULT NULL,
  `read_permission` int(11) DEFAULT '0' COMMENT '栏目稿件默认查看权限',
  `contribute_permission` int(11) DEFAULT '0',
  `link_url` varchar(255) DEFAULT NULL COMMENT '是外链节点时，外部链接地址',
  `upload_dir` varchar(50) DEFAULT NULL COMMENT '本栏目上传子目录',
  `index_template` varchar(255) DEFAULT NULL COMMENT '栏目页模板',
  `item_template` varchar(255) DEFAULT NULL COMMENT '栏目文稿模板',
  `creator_id` int(11) DEFAULT NULL COMMENT '创建者ID',
  `creator_name` varchar(50) DEFAULT NULL COMMENT '创建者名字',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `eng_name_UNIQUE` (`eng_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
